//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by w:\Visual Studio Projects\rsxplusplus\trunk\RSXPlusPlus.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_FILETYPES                   101
#define IDC_TRAY_SHOW                   103
#define IDC_COPY_HUB                    104
#define IDC_REMOVE_OFFLINE              104
#define IDC_DISABLE_SOUNDS              105
#define IDC_CDMDEBUG_WINDOW             106
#define IDC_CONNECT_ALL                 106
#define IDD_GENERALPAGE                 107
#define IDC_DISCONNECT_ALL              107
#define IDC_COLLAPSE_ALL                108
#define IDC_EXPAND_ALL                  109
#define IDC_SEGMENTONE                  110
#define IDC_SEGMENTTWO                  111
#define IDC_SEGMENTTHREE                112
#define IDC_SEGMENTFOUR                 113
#define IDC_SEGMENTFIVE                 114
#define IDC_SEGMENTSIX                  115
#define IDC_SEGMENTSEVEN                116
#define IDC_SEGMENTEIGHT                117
#define IDC_SEGMENTNINE                 118
#define IDC_SEGMENTTEN                  119
#define IDC_COPY_HUBNAME                120
#define IDC_COPY_HUBADDRESS             121
#define IDC_MENU_SLOWDISCONNECT         122
#define IDR_MAINFRAME                   123
#define IDC_DEBUG_FILTER_TEXT           124
#define IDC_COLLAPSED                   125
#define IDC_USER_CMD_PREVIEW            126
#define IDC_CLEAR                       127
#define IDC_COPY                        128
#define IDR_HUB                         129
#define IDC_PUB_LIST_DROPDOWN           130
#define IDC_SEARCH_PAUSE                130
#define IDC_HUBLIST                     131
#define IDC_EMOT                        131
#define IDC_OPEN_MY_LIST                132
#define IDC_SERVER                      133
#define IDC_EXTERNAL_IP                 133
#define ID_TOGGLE_QSEARCH               134
#define IDC_FILES                       135
#define IDC_CHANGE_PRIO_REALTIME        136
#define IDC_CHANGE_PRIO_HIGH            137
#define IDC_CHANGE_PRIO_ABOVE           138
#define IDC_CHANGE_PRIO_NORMAL          139
#define IDC_CHANGE_PRIO_BELOW           140
#define IDC_FILTER_UNDERLINE            140
#define IDC_CHANGE_PRIO_IDLE            141
#define IDC_FILTER_STRIKEOUT            141
#define IDC_RECONNECT_DISCONNECTED      142
#define IDC_COPY_BEGIN                  162
#define IDC_COPY_END                    163
#define IDD_LINE                        209
#define IDD_ADVANCEDPAGE                210
#define IDD_DOWNLOADPAGE                211
#define IDD_SHAREPAGE                   212
#define IDD_APPEARANCEPAGE              213
#define IDR_FLATTAB                     214
#define IDR_PUBLICHUBS                  215
#define IDR_SEARCH                      216
#define IDR_FAVORITES                   217
#define IDR_PRIVATE                     218
#define IDR_DIRECTORY                   219
#define IDR_NOTEPAD                     220
#define IDR_QUEUE                       221
#define IDR_SPY                         222
#define IDD_FAVORITEHUB                 223
#define IDR_USERS                       224
#define IDD_LOGPAGE                     224
#define IDD_UPLOADPAGE                  225
#define IDD_USER_COMMAND                230
#define IDR_FINISHED_DL                 231
#define IDR_FINISHED_UL                 232
#define IDR_ADLSEARCH                   233
#define IDD_ADLS_PROPERTIES             234
#define IDD_UCPAGE                      236
#define IDR_NET_STATS                   237
#define IDR_RECENTS                     238
#define IDR_UPLOAD_QUEUE                241
#define IDD_SOUNDS                      241
#define IDR_PRIVATE_OFF                 242
#define IDR_HUB_OFF                     243
#define IDD_FAKEDETECT                  248
#define IDD_OPERACOLORS                 249
#define IDD_AVIPREVIEW                  250
#define IDD_PREVIEW                     252
#define IDD_TOOLBARPAGE                 259
#define IDD_DOWNLOADDIR                 260
#define IDD_FAVORITE_DIRSPAGE           261
#define IDD_CLIENTS_PAGE                264
#define IDR_CDM                         270
#define IDD_UPDATE                      274
#define IDR_UPDATE                      276
#define IDD_RAW_CHEAT                   276
#define IDB_SHUTDOWN                    278
#define IDD_MAGNET                      281
#define IDI_MAGNET                      283
#define IDD_HASH_PROGRESS               284
#define IDR_TREE_YES                    285
#define IDR_TREE_NO                     286
#define IDD_POPUPS                      287
#define IDD_SDCPAGE                     288
#define IDD_USERLIST_COLOURS            289
#define IDD_HUB_LIST                    290
#define IDD_WINDOWSPAGE                 292
#define IDD_EMOTICONS_DLG               293
#define IDD_FILELIST_DETECTOR_PAGE      294
#define IDD_NETWORKPAGE                 296
#define IDD_CERTIFICATESPAGE            297
#define IDD_QUEUEPAGE                   298
#define IDD_AUTOSEARCH_DLG              299
#define IDD_ADD_FILELIST_PROFILE        300
#define IDD_PARAMS                      301
#define IDD_PARAM_DLG                   302
#define IDR_TUSER                       305
#define IDB_BITMAP1                     306
#define IDB_BITMAP2                     308
#define IDB_BITMAP3                     309
#define IDD_IP_PAGE                     310
#define IDD_ADD_IPWATCH                 313
#define IDD_AUTOSEARCH                  314
#define IDD_RAW_PAGE                    317
#define IDD_RAW_DLG                     318
#define IDR_PEERGUARDIAN                318
#define IDC_FAV_GROUPS                  324
#define IDD_FAV_TAB_RAW                 324
#define IDD_PLUGINS_LIST                326
#define IDD_DETECTION_ENTRY             328
#define IDD_ADD_STRING_PAIR             329
#define IDP_RSX_SPLASH                  332
#define IDP_ARROWS                      333
#define IDP_EMOTICON                    335
#define IDP_FAVSTATES                   336
#define IDP_FLAGS                       338
#define IDP_FOLDERS                     339
#define IDP_O_SETTINGS_DLG              340
#define IDP_SEARCH_TYPES                341
#define IDP_SPEEDS                      342
#define IDP_STATE                       343
#define IDP_TOOLBAR                     344
#define IDP_TOOLBAR20                   345
#define IDP_TOOLBAR20_HOT               346
#define IDP_TSPEEDS                     347
#define IDP_TSPEEDSBW                   348
#define IDP_USERS                       349
#define IDP_FAVTABS                     350
#define IDR_TOGGLE_QSEARCH              351
#define IDD_ADL_POINTS_SETTINGS         352
#define IDR_RT_MANIFEST1                353
#define IDD_SHUTDOWN_DLG                354
#define IDC_REFRESH                     1000
#define IDC_NICK                        1001
#define IDC_EMAIL                       1002
#define IDC_DESCRIPTION                 1003
#define IDC_CONNECTIONTYPE              1005
#define IDC_MYINFO_CONNECTION           1005
#define IDC_USERS                       1006
#define IDC_ACTIVE                      1006
#define IDC_CONNECTION                  1006
#define IDC_PASSIVE                     1007
#define IDC_PORT                        1008
#define IDC_DIRECTORIES                 1009
#define IDC_PORT_TCP                    1009
#define IDC_REMOVE_ALL                  1010
#define IDC_ADD                         1011
#define IDC_REMOVE                      1012
#define IDC_REMOVE_EX                   1013
#define IDC_TOTAL                       1014
#define IDC_ADD_EX                      1014
#define IDC_SLOTS                       1015
#define IDC_SLOTSPIN                    1016
#define IDC_TRANSFERS                   1017
#define IDC_DOWNLOADDIR                 1017
#define IDC_CONNECT                     1018
#define IDC_BROWSEDIR                   1018
#define IDC_RESULTS                     1019
#define IDC_LINE                        1019
#define IDC_EXTRA_SLOTS2                1019
#define IDC_DOWNLOADDIRTO               1020
#define IDC_EXTRASPIN                   1020
#define IDC_PRIVATEMESSAGE              1021
#define IDC_VERSION                     1021
#define IDC_GETLIST                     1022
#define IDC_ROLLBACK                    1022
#define IDC_RECHECK                     1023
#define IDC_EDIT                        1026
#define IDC_NOTEPAD                     1027
#define IDC_AWAY                        1028
#define IDC_SEARCH_ALTERNATES           1029
#define IDC_SELWINCOLOR                 1031
#define IDC_SELTEXT                     1032
#define IDC_SHAREHIDDEN                 1035
#define IDC_QUEUE                       1037
#define IDC_HUBNICK                     1041
#define IDC_HUBPASS                     1042
#define IDC_NEWFAV                      1042
#define IDC_HUBNAME                     1043
#define IDC_SOURCE_TYPE                 1044
#define IDC_RAW_ONE                     1044
#define IDC_PROTECTED_USERS             1044
#define IDC_CHECK_PROTECTED_USER        1044
#define IDC_SIZE_TYPE                   1045
#define IDC_RAW_TWO                     1045
#define IDC_RAW_THREE                   1046
#define IDC_HUBDESCR                    1047
#define IDC_HUBADDR                     1048
#define IDC_RAW_FOUR                    1049
#define IDC_SETTINGS_LIST_CONFIG        1049
#define IDC_FORCE                       1050
#define IDC_RAW_FIVE                    1050
#define IDC_BUFFERSIZE                  1051
#define IDC_LANGUAGE                    1052
#define IDC_BROWSE                      1053
#define IDC_THANKS                      1055
#define IDC_DOWNLOADS                   1056
#define IDC_SLOTSSPIN                   1057
#define IDC_MAXSPEED                    1058
#define IDC_SPEEDSPIN                   1059
#define IDC_FAVUSERS                    1060
#define IDC_PROXY                       1060
#define IDC_ADD_TO_FAVORITES            1061
#define IDC_FILESPIN                    1062
#define IDC_HELP_HOMEPAGE               1063
#define IDC_LOG_DIRECTORY               1065
#define IDC_BROWSE_LOG                  1066
#define IDC_HELP_DISCUSS                1067
#define IDC_HELP_FAQ                    1069
#define IDC_SEARCH_SPY                  1070
#define IDC_LATEST                      1071
#define IDC_PRIVATE_MESSAGE_BEEP        1072
#define IDC_PRIVATE_MESSAGE_BEEP_OPEN   1073
#define IDC_MIN_UPLOAD_SPEED            1074
#define IDC_SETTINGS_TYPE               1074
#define IDC_MIN_UPLOAD_SPIN             1075
#define IDC_CHEVRON                     1076
#define IDC_OPEN_FILE_LIST              1077
#define IDC_TOTALS                      1077
#define IDC_SEARCH                      1078
#define IDC_RATIO                       1078
#define IDC_CLOSE_WINDOW                1080
#define IDC_FIND                        1081
#define IDC_NEXT                        1082
#define IDC_FINISHED                    1084
#define IDC_TEMP_DOWNLOAD_DIRECTORY     1084
#define IDC_CHANGE                      1084
#define IDC_BROWSETEMPDIR               1085
#define IDC_SOCKS_RESOLVE               1086
#define IDC_PROGRESS_BUMPED             1086
#define IDC_REMOVEALL                   1087
#define IDC_SOCKS_SERVER                1090
#define IDC_SOCKS_PORT                  1091
#define IDC_SOCKS_USER                  1092
#define IDC_SOCKS_PASSWORD              1093
#define IDC_FREESLOTS                   1094
#define IDC_TTHONLY                     1095
#define IDC_COPY_NICK                   1096
#define IDC_ADVANCED_BOOLEANS           1096
#define IDC_ADD_MENU                    1097
#define IDC_MOVE                        1098
#define IDC_REMOVE_MENU                 1098
#define IDC_MENU_ITEMS                  1099
#define IDC_CHANGE_MENU                 1100
#define IDC_UPDATE_HISTORY_TEXT         1100
#define IDC_NAME                        1101
#define IDC_COMMAND                     1102
#define IDC_PROGRESS_OVERRIDE           1102
#define IDC_HUB                         1103
#define IDC_PROGRESS_OVERRIDE2          1103
#define IDC_TIME                        1103
#define IDC_SHUTDOWNTIMEOUT             1104
#define IDC_PROGRESS_SEGMENT_SHOW       1104
#define IDC_COMMAND_DESCRIPTION         1105
#define IDC_SETTINGS_ODC_MENUBAR_RIGHT  1105
#define IDC_APPEARANCE_BOOLEANS         1106
#define IDC_SETTINGS_ODC_MENUBAR_LEFT   1106
#define IDC_DEFAULT_AWAY_MESSAGE        1107
#define IDC_INTERVAL                    1107
#define IDC_CLOSE_DISCONNECTED          1108
#define IDC_MATCH                       1108
#define IDC_OPEN_FOLDER                 1109
#define IDC_MAX_TAB_ROWS                1109
#define IDC_OPEN_FILE                   1110
#define IDC_SETTINGS_ODC_MENUBAR_BUMPED 1110
#define IDC_FILE_ADL_SEARCH             1111
#define IDC_SHUTDOWN                    1112
#define IDC_ADLLIST                     1113
#define IDC_MOVE_UP                     1114
#define IDC_MOVE_DOWN                   1115
#define IDC_HUBUSERDESCR                1116
#define IDC_FINISHED_UL                 1117
#define IDC_SEARCH_STRING               1118
#define IDC_SEARCH_HISTORY              1118
#define IDC_DEST_DIR                    1119
#define IDC_IS_ACTIVE                   1120
#define IDC_MIN_FILE_SIZE               1121
#define IDC_MAX_FILE_SIZE               1122
#define IDC_AUTOQUEUE                   1123
#define IDC_GO_TO_DIRECTORY             1124
#define IDC_IS_FORBIDDEN                1124
#define IDC_MATCH_QUEUE                 1125
#define IDC_ADLS_KICK_STRING            1126
#define IDC_IS_REGEXP                   1127
#define IDC_ADLS_COMMENT                1128
#define IDC_VIEW_AS_TEXT                1129
#define IDC_OVER_RIDE_POINTS            1129
#define IDC_PAGE                        1130
#define IDC_IS_CASE_SENSITIVE           1130
#define IDC_NET_STATS                   1131
#define IDC_SETTINGS_PERSONAL_INFORMATION 1132
#define IDC_SETTINGS_NICK               1133
#define IDC_SETTINGS_EMAIL              1134
#define IDC_SETTINGS_DESCRIPTION        1135
#define IDC_SETTINGS_ODC_SHUTDOWNTIMEOUT 1135
#define IDC_SETTINGS_IP                 1138
#define IDC_SETTINGS_PORT               1139
#define IDC_SETTINGS_SOCKS5_IP          1140
#define IDC_SETTINGS_SOCKS5_PORT        1141
#define IDC_SETTINGS_SOCKS5_USERNAME    1142
#define IDC_SETTINGS_SOCKS5_PASSWORD    1143
#define IDC_SETTINGS_UPLOAD_SPEED       1143
#define IDC_SETTINGS_UPLOAD_LINE_SPEED  1143
#define IDC_SETTINGS_DIRECTORIES        1144
#define IDC_SETTINGS_INCOMING           1144
#define IDC_SETTINGS_UPLOAD_SPEED2      1144
#define IDC_SETTINGS_DOWNLOAD_DIRECTORY 1145
#define IDC_SETTINGS_UNFINISHED_DOWNLOAD_DIRECTORY 1146
#define IDC_SETTINGS_PORT_TCP           1146
#define IDC_SETTINGS_DOWNLOAD_LIMITS    1147
#define IDC_SETTINGS_DOWNLOADS_MAX      1148
#define IDC_SETTINGS_DOWNLOADS_SPEED_PAUSE 1149
#define IDC_SETTINGS_SPEEDS_NOT_ACCURATE 1150
#define IDC_SETTINGS_PUBLIC_HUB_LIST    1151
#define IDC_SETTINGS_PUBLIC_HUB_LIST_URL 1152
#define IDC_SETTINGS_PUBLIC_HUB_LIST_HTTP_PROXY 1153
#define IDC_SETTINGS_SHARED_DIRECTORIES 1154
#define IDC_SETTINGS_FILES_MAX          1154
#define IDC_SETTINGS_SHARE_SIZE         1155
#define IDC_SETTINGS_UPLOADS_MIN_SPEED  1156
#define IDC_SETTINGS_UPLOADS_SLOTS      1157
#define IDC_SETTINGS_APPEARANCE_OPTIONS 1159
#define IDC_SETTINGS_DEFAULT_AWAY_MSG   1160
#define IDC_SETTINGS_LANGUAGE_FILE      1161
#define IDC_SETTINGS_REQUIRES_RESTART   1162
#define IDC_SETTINGS_LOGGING            1163
#define IDC_SETTINGS_LOG_DIR            1164
#define IDC_SETTINGS_ROLLBACK           1167
#define IDC_SETTINGS_WRITE_BUFFER       1169
#define IDC_SETTINGS_MAX_TAB_ROWS       1170
#define IDC_SETTINGS_USER_MENU          1171
#define IDC_SETTINGS_KB                 1172
#define IDC_SETTINGS_B                  1173
#define IDC_SETTINGS_KBPS               1174
#define IDC_ADD_AS_FAVORITE             1175
#define IDC_SETTINGS_SEARCH_HISTORY     1178
#define IDC_HELP_DONATE                 1179
#define IDC_ADLSP_SEARCH                1184
#define IDC_ADLSP_TYPE                  1185
#define IDC_ADLSP_SIZE_MIN              1186
#define IDC_ADLSP_SIZE_MAX              1187
#define IDC_ADLSP_UNITS                 1188
#define IDC_ADLSP_DESTINATION           1189
#define IDC_SETTINGS_SEPARATOR          1194
#define IDC_SETTINGS_RAW                1195
#define IDC_SETTINGS_CHAT               1196
#define IDC_SETTINGS_PM                 1197
#define IDC_SETTINGS_HUB_MENU           1198
#define IDC_SETTINGS_SEARCH_MENU        1200
#define IDC_SETTINGS_CONTEXT            1201
#define IDC_SETTINGS_PARAMETERS         1202
#define IDC_SETTINGS_NAME               1203
#define IDC_SETTINGS_COMMAND            1204
#define IDC_SETTINGS_HUB                1205
#define IDC_SETTINGS_TO                 1206
#define IDC_RESULT                      1207
#define IDC_SETTINGS_FORMAT             1207
#define IDC_PREVIEW_BROWSE              1208
#define IDC_REFRESH_FILE_LIST           1210
#define IDC_SETTINGS_ONCE               1212
#define IDC_OPEN_DOWNLOADS              1213
#define IDC_SETTINGS_UPLOAD_BAR_COLOR   1214
#define IDC_PREVIEW_ARGUMENTS           1214
#define IDC_SETTINGS_DOWNLOAD_BAR_COLOR 1215
#define IDC_PREVIEW_EXTENSION           1215
#define IDC_AUTOSEGMENT                 1216
#define IDC_SETTINGS_SEGMENT_BAR_COLOR  1216
#define IDC_COPY_TTH                    1217
#define IDC_DONTBEGIN                   1217
#define IDC_EDIT1                       1218
#define IDC_CLIENT_NAME                 1218
#define IDC_CHUNKCOUNT                  1218
#define IDC_CLIENT_VERSION              1219
#define IDC_ADD_STRING_PAIR_SECOND      1219
#define IDC_CLIENT_TAG                  1220
#define IDC_STATIC2                     1221
#define IDC_TOOLBAR_ACTUAL              1221
#define IDC_CLIENT_EXTENDED_TAG         1221
#define IDC_DU                          1221
#define IDC_POPUPTYPE                   1221
#define IDC_STATIC3                     1222
#define IDC_CLIENT_LOCK                 1222
#define IDC_CLIENT_PK                   1223
#define IDC_MAX_HASH_SPEED              1223
#define IDC_TOOLBAR_IMAGE               1224
#define IDC_CLIENT_SUPPORTS             1224
#define IDC_TREE1                       1224
#define IDC_STATICb                     1225
#define IDC_IMAGEBROWSE                 1225
#define IDC_CLIENT_TESTSUR_RESPONSE     1225
#define IDC_SETTINGS_MAX_HASH_SPEED     1225
#define IDC_SHOW_SPEED_CHECK            1225
#define IDC_TOOLBAR_POSSIBLE            1226
#define IDC_CLIENT_USER_CON_COM         1226
#define IDC_SETTINGS_MBS                1226
#define IDC_MOUSE_OVER                  1227
#define IDC_CLIENT_STATUS               1227
#define IDC_NORMAL                      1228
#define IDC_TOOLBAR_IMAGE_BOX           1229
#define IDC_VERSION_MISMATCH            1229
#define IDC_DOWNLOADDIR_DIR             1230
#define IDC_USE_EXTRA_VERSION           1230
#define IDC_TTH                         1230
#define IDC_DOWNLOADDIR_NAME            1231
#define IDC_DOWNLOADDIR_EXT             1232
#define IDC_CLIENT_ITEMS                1232
#define IDC_MAGNET_QUEUE                1232
#define IDC_ADD_CLIENT                  1233
#define IDC_MAGNET_SEARCH               1233
#define IDC_CLIENT_FORMATTED_TAG        1233
#define IDC_CHANGE_CLIENT               1234
#define IDC_MAGNET_REMEMBER             1234
#define IDC_MOVE_CLIENT_UP              1235
#define IDC_MAGNET_HASH                 1235
#define IDC_MOVE_CLIENT_DOWN            1236
#define IDC_CLIENT_CONNECTION           1236
#define IDC_MAGNET_NAME                 1236
#define IDC_REMOVE_CLIENT               1237
#define IDC_MAGNET_NOTHING              1237
#define IDC_ADD_LINE                    1238
#define IDC_MAGNET_DISP_NAME            1238
#define IDC_MAGNET_DISP_HASH            1239
#define IDC_MAGNET_TEXT                 1240
#define IDC_SETTINGS_TIME_STAMPS_FORMAT 1241
#define IDC_TIME_STAMPS_FORMAT          1242
#define IDC_CLIENT_CHEATING_DESCRIPTION 1243
#define IDC_SETTINGS_ONLY_HASHED        1243
#define IDC_FH_HUB                      1243
#define IDC_COMMENT                     1244
#define IDC_FH_IDENT                    1244
#define IDC_FH_NAME                     1245
#define IDC_MAXCOMPRESS                 1246
#define IDC_HASH_PROGRESS               1246
#define IDC_FH_ADDRESS                  1246
#define IDC_MAX_COMPRESSION             1247
#define IDC_HASH_INDEXING               1247
#define IDC_FH_HUB_DESC                 1247
#define IDC_MAX_COMP_SPIN               1248
#define IDC_FILES_PER_HOUR              1248
#define IDC_FH_NICK                     1248
#define IDC_RELOAD_CLIENTS              1249
#define IDC_HASH_SPEED                  1249
#define IDC_FH_PASSWORD                 1249
#define IDC_MYINFO_COUNTER              1249
#define IDC_FH_USER_DESC                1250
#define IDC_MYINFO_TIME                 1250
#define IDC_FAKE_SHARE_ITEMS            1250
#define IDC_TIME_LEFT                   1251
#define IDC_LOAD_BACKUP                 1251
#define IDC_CTE_COUNTER                 1251
#define IDC_ADD_FAKE_SHARE              1251
#define IDC_SETTINGS_FAVORITE_DIRECTORIES 1252
#define IDC_CTE_TIME                    1252
#define IDC_CHANGE_FAKE_SHARE           1252
#define IDC_LOAD_BACKUP2                1252
#define IDC_SHUTDOWN_SPIN               1253
#define IDC_STATISTICS                  1253
#define IDC_FAVORITE_DIRECTORIES        1253
#define IDC_KB                          1254
#define IDC_SETTINGS_DIRS_EX            1254
#define IDC_SEG_NUMBER                  1255
#define IDC_CURRENT_FILE                1255
#define IDC_REMOVE_FAKE_SHARE           1255
#define IDC_DIRS_EX                     1255
#define IDC_SEG_NUMBER_SPIN             1256
#define IDC_INTERVAL_SPIN               1256
#define IDC_LIST_ADD                    1256
#define BAA                             1257
#define IDC_SEARCH_EDIT                 1257
#define IDC_MATCH_SPIN                  1257
#define IDC_LIST_EDIT_BOX               1257
#define CAA                             1258
#define IDC_SEARCH_SPIN                 1258
#define IDC_LIST_UP                     1258
#define IDC_VALUE                       1258
#define DAA                             1259
#define IDC_BEGIN_EDIT                  1259
#define IDC_LIST_DOWN                   1259
#define IDC_FILELIST_PROFILE_CHEAT      1259
#define FAKE_SET                        1260
#define IDC_BEGIN_SPIN                  1260
#define IDC_LIST_REMOVE                 1260
#define IDC_FD_OPTIONS                  1260
#define IDC_LIST_DESC                   1261
#define IDC_TIMEOUTS                    1261
#define AAA                             1262
#define IDC_LIST_LIST                   1262
#define IDC_DISCONNECTS                 1262
#define IDC_SOUNDLIST                   1263
#define IDC_RENAME                      1263
#define IDC_MAXIMUM_FILELIST_SIZE       1263
#define IDC_UPDATE_URL                  1264
#define IDC_REGEXP_TESTER_TEXT          1264
#define IDC_LIST_EDIT                   1264
#define IDC_CHEAT                       1264
#define IDC_NAME_ONE                    1264
#define IDC_RENAME_EX                   1264
#define IDC_MYINFO_ADDRESS              1265
#define IDC_NAME_TWO                    1265
#define IDC_CHANGE_COLOR                1266
#define IDC_PORT_UDP                    1266
#define IDC_NAME_THREE                  1266
#define IDC_MINIMUM_FILELIST_SIZE       1266
#define IDC_USERLIST_IMAGE              1267
#define IDC_SETTINGS_PORT_UDP           1267
#define IDC_ISP_ADDRESS                 1267
#define IDC_NAME_FOUR                   1267
#define IDC_USERLIST                    1268
#define IDC_NAME_FIVE                   1268
#define IDC_IMPORT                      1269
#define IDC_BACKGROUND_IMAGE            1269
#define IDC_CLIENT_ADDRESS              1269
#define IDC_NAME_SIX                    1269
#define IDC_EXPORT                      1270
#define IDC_BACK_IMAGE                  1270
#define IDC_FILTER_PAGE_ITEMS           1270
#define IDC_TEXT_ONE                    1270
#define IDC_SETTINGS_GET_USER_COUNTRY   1271
#define IDC_ADD_FILTER                  1271
#define IDC_TEXT_TWO                    1271
#define IDC_CHANGE_FILTER               1272
#define IDC_TEXT_THREE                  1272
#define IDC_UP_COMBO                    1273
#define IDC_LOG_FORMAT                  1273
#define IDC_REMOVE_FILTER               1273
#define IDC_TEXT_FOUR                   1273
#define IDC_DOWN_COMBO                  1274
#define IDC_LOG_FILE                    1274
#define IDC_TEXT_FIVE                   1274
#define IDC_HL_ITEMS                    1274
#define IDC_SLASH                       1275
#define IDC_LOG_OPTIONS                 1275
#define IDC_TEXT_SIX                    1275
#define IDC_ADD_HL                      1275
#define IDC_SETTINGS_FILE_NAME          1276
#define IDC_CHANGE_HL                   1276
#define IDC_ALTERNATE_COLOR             1277
#define IDC_FSTRING                     1277
#define IDC_REMOVE_HL                   1277
#define IDC_FAKE_BOOLEANS               1278
#define IDC_SETTINGS_FILELIST_MENU      1278
#define IDC_PURGE                       1279
#define IDC_KBPS                        1280
#define IDC_IPWATCH_LIST                1280
#define IDC_MINUTES                     1281
#define IDC_SEARCH_HISTORY_SPIN         1281
#define IDC_KBPS2                       1281
#define IDC_ADD_WATCH                   1281
#define IDC_PLAY                        1282
#define IDC_CLIPBOARD_ONE               1282
#define IDC_CHANGE_WATCH                1282
#define IDC_MINUTES2                    1282
#define IDC_POPUPLIST                   1283
#define IDC_CLIPBOARD_TWO               1283
#define IDC_REMOVE_WATCH                1283
#define IDC_COMBO1                      1284
#define IDC_CLIPBOARD_THREE             1284
#define IDC_EDIT2                       1285
#define IDC_CLIPBOARD_FOUR              1285
#define IDC_PD_MULTISOURCE              1285
#define IDC_IPW_MATCH_TYPE              1285
#define IDC_EDIT3                       1286
#define IDC_BIND_ADDRESS                1286
#define IDC_CLIPBOARD_FIVE              1286
#define IDC_PD_FAKECLIENT               1286
#define IDC_STATIC1                     1287
#define IDC_SETTINGS_BIND_ADDRESS_HELP  1287
#define IDC_CLIPBOARD_SIX               1287
#define IDC_PD_OP_CLIENT                1287
#define IDC_REGEXP_TESTER_BUTTON        1288
#define IDC_FAKE_SHARE_ACCEPTED         1288
#define IDC_SECOND                      1288
#define IDC_ACTION                      1289
#define IDC_STYLES_SELECTOR             1289
#define IDC_S                           1290
#define IDC_FAKE_SHARE_SET              1290
#define IDC_FLAT                        1291
#define IDC_S2                          1291
#define IDC_FLAT_SPIN                   1292
#define IDC_DEFAULT                     1293
#define IDC_CONN_BORDER                 1294
#define IDC_CLIENT_PROFILE_RAW          1295
#define IDC_MULTISOURCE                 1295
#define IDC_SETTINGS_OUTGOING           1295
#define IDC_REGEXP_TESTER_COMBO         1296
#define IDC_LISTLEN                     1296
#define IDC_MULTISOURCE_COMBO           1296
#define IDC_PUB_LIST_CONFIG             1297
#define IDC_ODC_STYLE                   1297
#define IDC_OVERRIDE                    1297
#define IDC_CHANGE_RAW                  1297
#define IDC_CLIENT_PROFILE_RAW2         1297
#define IDC_ADLSEARCH_COMMENT           1297
#define IDC_WINDOWS_STARTUP             1298
#define IDC_SETTINGS_PORTS              1298
#define IDC_SETTINGS_AUTO_OPEN          1299
#define IDC_SETTINGS_BIND_ADDRESS       1299
#define IDC_PERCENT_HASHED_SPIN         1299
#define IDC_SETTINGS_WINDOWS_OPTIONS    1300
#define IDC_ADLSEARCH_ACTION            1300
#define IDC_PRIO_HIGHEST_SIZE           1300
#define IDC_WINDOWS_OPTIONS             1301
#define IDC_ADLSEARCH_RAW_ACTION        1301
#define IDC_PRIO_HIGH_SIZE              1301
#define IDC_REFRESH_SPIN                1301
#define IDC_DIRECT                      1302
#define IDC_PRIO_NORMAL_SIZE            1302
#define IDC_ROLLBACK_SPIN               1302
#define IDC_ADLSEARCH_ACTION2           1302
#define IDC_FIREWALL_UPNP               1303
#define IDC_PRIO_LOW_SIZE               1303
#define IDC_SHUTDOWNACTION              1303
#define IDC_PARAM_ITEMS                 1303
#define IDC_FIREWALL_NAT                1304
#define IDC_SETTINGS_PRIO_HIGHEST       1304
#define IDC_READ_SPIN                   1304
#define IDC_POPUPGROUP                  1304
#define IDC_PARAM_NAME                  1304
#define IDC_FIREWALL_PASSIVE            1305
#define IDC_SETTINGS_PRIO_HIGH          1305
#define IDC_AUTO_SEARCH_LIMIT_SPIN      1305
#define IDC_PARAM_REGEXP                1305
#define IDC_DIRECT_OUT                  1306
#define IDC_SETTINGS_PRIO_NORMAL        1306
#define IDC_TAB_SPIN                    1306
#define IDC_CHECK_CLIENTS               1306
#define IDC_SOCKS5                      1307
#define IDC_SETTINGS_PRIO_LOW           1307
#define IDC_WRITE_SPIN                  1307
#define IDC_CHECK2                      1307
#define IDC_CHECK_FILELISTS             1307
#define IDC_FILTER_BOLD                 1307
#define IDC_BAD_CLIENT                  1307
#define IDC_USE_REGEXP_OR_WILD          1307
#define IDC_CHECK_MISMATCH              1307
#define IDC_SHOW_CC                     1307
#define IDC_SETTINGS_KB3                1308
#define IDC_HASH_SPIN                   1308
#define IDC_SLEEP_TIME_S                1308
#define IDC_FILTER_ITALIC               1308
#define IDC_FILELIST_DETECTOR_LIST      1308
#define IDC_FILELIST_DLG_DETECT_STRING  1308
#define IDC_FIREWALL_NAT_PMP            1308
#define IDC_SETTINGS_KB4                1309
#define IDC_BUFFER_SPIN                 1309
#define IDC_FAV_SEARCH_INTERVAL         1309
#define IDC_CHECK_DELAY_S               1309
#define IDC_FILELIST_PROFILE_RAW        1309
#define IDC_FILTER_BOLD2                1309
#define IDC_FAV_SEARCH_INTERVAL_BOX     1310
#define IDC_SETTINGS_KB5                1310
#define IDC_DOWNCONN_SPIN               1310
#define IDC_MAX_TESTSURS_S              1310
#define IDC_FILELIST_PROFILE_NAME       1310
#define IDC_FAV_SEARCH_INTERVAL_SPIN    1311
#define IDC_SETTINGS_KB6                1311
#define IDC_RAW_PAGE_ACTION_CTN         1311
#define IDC_MAX_FILELISTS_S             1311
#define IDC_HASH_ERROR_RAW              1311
#define IDC_SETTINGS_AUTOPRIO           1312
#define IDC_RAW_PAGE_RAW_CTN            1312
#define IDC_SHOW_CHEAT_S                1312
#define IDC_PERCENT_HASHED              1312
#define IDC_SETTINGS_SEGMENT            1313
#define IDC_BOLD_BOOLEANS               1313
#define IDC_SLOTS_GROUP                 1313
#define IDC_RAW_PAGE_ACTION             1313
#define IDC_FD_PROTECT                  1313
#define IDC_FILELIST_PROFILE_DETECT     1313
#define IDC_SETTINGS_BOLD_CONTENTS      1314
#define IDC_RAW_PAGE_RAW                1314
#define IDC_CHECK1                      1314
#define IDC_USE_AB                      1314
#define IDC_CHECK_MYINFO                1314
#define IDC_USE_CHAT_FILTER             1314
#define IDC_FILTER_USECOLOR             1314
#define IDC_USE_TRANSPARENT             1314
#define IDC_WATCH_DISPLAY_CHEAT         1314
#define IDC_AS_DISPLAY                  1314
#define IDC_CP_PD_LIMITER               1314
#define IDC_INDICATE_SPEEDS             1314
#define IDC_SHOW_CHEAT_S2               1314
#define IDC_USE_SDL_KICK                1314
#define IDC_HAS_FONT_COLOR              1314
#define IDC_DISPLAY_CHEAT               1314
#define IDC_RAW_LUA                     1314
#define IDC_ENABLE                      1314
#define IDC_SHOW_IP                     1314
#define IDC_NAT_PMP_RANDOM_PORTS        1314
#define IDC_SETTINGS_CONFIRM_OPTIONS    1315
#define IDC_PROFILE_MESSAGE             1315
#define IDC_ADD_ACTION                  1315
#define IDC_SPIN1                       1315
#define IDC_CHECK_FAKE_SHARE            1315
#define IDC_TESTSURS_SPIN               1315
#define IDC_ENABLE_IPWATCH              1315
#define IDC_CP_PD_OP_CLIENT             1315
#define IDC_USE_HL                      1315
#define IDC_WATCH_USE_REGEXP            1315
#define IDC_PERCENT_FAKE_SHARE_TOLERATED_SPIN 1315
#define IDC_HAS_BG_COLOR                1315
#define IDC_CP_ID_SPIN                  1315
#define IDC_MP_ID_SPIN                  1315
#define IDC_CONFIRM_OPTIONS             1316
#define IDC_RENAME_ACTION               1316
#define IDC_AB_LEVEL                    1316
#define IDC_CP_PD_FAKE_CLIENT           1316
#define IDC_CHECK_AUTOSEARCH            1316
#define IDC_SOCKET_IN_BUFFER            1317
#define IDC_REMOVE_ACTION               1317
#define IDC_AB_GROUP                    1317
#define IDC_CHECK5                      1317
#define IDC_CP_PD_MULTISOURCE           1317
#define IDC_HAS_FONT_COLOR2             1317
#define IDC_HL_DISPLAY_POPUP            1317
#define IDC_FILTER_HAS_FONT_COLOR       1317
#define IDC_SOCKET_OUT_BUFFER           1318
#define IDC_TLS_CERTIFICATE_FILE        1318
#define IDC_PORT_TLS                    1318
#define IDC_ADD_RAW                     1318
#define IDC_SKIPLIST_GP                 1318
#define IDC_HL_FLASH_WINDOW             1318
#define IDC_SETTINGS_SOCKET_OUT_BUFFER  1319
#define IDC_MOVE_RAW_UP                 1319
#define IDC_PROFILE_COUNT               1319
#define IDC_RSX_BOOLEANS                1319
#define IDC_SKIPLIST_SHARE              1319
#define IDC_SETTINGS_SOCKET_IN_BUFFER   1320
#define IDC_REMOVE_RAW                  1320
#define IDC_PROFILE_VERSION             1320
#define IDC_WINAMP_FORMAT               1320
#define IDC_HL_PLAY_SOUND               1320
#define IDC_MOVE_RAW_DOWN               1321
#define IDC_MPC_FORMAT                  1321
#define IDC_MYINFO_ACTIVE               1321
#define IDC_RAW                         1322
#define IDC_ITUNES_FORMAT               1322
#define IDC_RSXADVANCED_BOOLEANS        1322
#define IDC_CLIENT_ACTIVE               1322
#define IDC_RAW_NAME                    1323
#define IDC_ISP_ACTIVE                  1323
#define IDC_BW_SIMPLE                   1324
#define IDC_RAW_TIME                    1324
#define IDC_FH_ACTION                   1324
#define IDC_CON_CHECK                   1324
#define IDC_BW_BOTH                     1325
#define IDC_FH_RAW                      1325
#define IDC_SETTINGS_NOMINALBW          1326
#define IDC_HIDE_SHARE                  1326
#define IDC_HELP_TRANSLATIONS           1327
#define IDC_FAV_EMAIL                   1327
#define IDC_PG_ENABLE                   1327
#define IDC_FILTER_BOX                  1328
#define IDC_USE_FILTER_FAV              1328
#define IDC_PG_GP                       1328
#define IDC_DETECTOR_ITEMS              1329
#define IDC_FILTER_BOX2                 1329
#define IDC_FAV_AWAY_MSG                1329
#define IDC_RELOAD_BL                   1329
#define IDC_FORBIDDENC                  1330
#define IDC_USE_HIGHLIGHT_FAV           1330
#define IDC_PG_STATUS                   1330
#define IDC_PG_DOWN                     1331
#define IDC_PG_UP                       1332
#define IDC_BACK                        1333
#define IDC_ADLS_POINTS                 1333
#define IDC_ADLS_POINTS_SPIN            1334
#define IDC_PG_SEARCH                   1334
#define IDC_SEP                         1336
#define IDC_LIST                        1337
#define IDC_TIMEOUT_SPIN                1337
#define IDC_GETIP                       1337
#define IDC_RELOAD                      1338
#define IDC_IPUPDATE                    1338
#define IDC_TAG                         1339
#define IDC_DISCONNECT_SPIN             1339
#define IDC_PRIO_FILE                   1339
#define IDC_FORMATTED_TAG               1340
#define IDC_DISCONNECT_NO               1340
#define IDC_HIGHEST_STR                 1340
#define IDC_EXTENDED_TAG                1341
#define IDC_LOWEST_STR                  1341
#define IDC_SHARED                      1342
#define IDC_HIGHEST                     1342
#define IDC_PROFILE_RAW                 1343
#define IDC_LOWEST                      1343
#define IDC_STATUS                      1344
#define IDC_CHEATING_DESCRIPTION        1345
#define IDC_FILELISTS_SPIN              1345
#define IDC_CHECK_DELAY_SPIN            1348
#define IDC_SLEEP_TIME_SPIN             1350
#define IDC_FILTER_FONTCOLOR            1351
#define IDC_FILTER_BACKCOLOR            1352
#define IDC_PLAYER_COMBO                1352
#define IDC_AUTOSEARCH_ITEMS            1352
#define IDC_AS_SEARCH_STRING            1353
#define IDC_STEALTHY_STYLE              1354
#define IDC_PROGRESS                    1354
#define IDC_UPDATE_AB                   1354
#define IDC_SEARCH_FAKE_DLG_SEARCH_STRING 1354
#define IDC_SPEED_STR                   1355
#define IDC_OVERRIDE_FAV                1355
#define IDC_TOP_SPEED                   1356
#define IDC_OVERRIDE_CUSTOM             1356
#define IDC_MISC_GP                     1357
#define IDC_AUTOSEARCH_ENABLE_TIME      1357
#define IDC_SPEED_UP_STR                1358
#define IDC_AUTOSEARCH_EVERY            1358
#define IDC_TOP_UP_SPEED                1359
#define IDC_AUTOSEARCH_SPIN             1359
#define IDC_AUTOSEARCH_RECHECK_TIME     1360
#define IDC_MISC_IGNORE                 1361
#define IDC_AUTOSEARCH_RECHECK_SPIN     1361
#define IDC_AS_RAW                      1362
#define IDC_ADD_SRCH_STR_COMMAND_STATIC 1363
#define IDC_TRANSPARENT_LEVEL           1364
#define IDC_AS_ACTION_STATIC            1364
#define IDC_AB_SPIN                     1365
#define IDC_AS_CHEAT                    1365
#define IDC_WATCH_ACTION_CMD            1366
#define IDC_WATCH_IP                    1367
#define IDC_IGNORE_ADD                  1368
#define IDC_WATCH_ACTION                1368
#define IDC_AUTOSEARCH_ENABLE           1368
#define IDC_UPDATE_BL                   1368
#define IDC_IGNORELIST                  1369
#define IDC_WATCH_CHEAT                 1369
#define IDC_IGNORELIST_EDIT             1370
#define IDC_ADD_SRCH_STR_TYPE_STATIC    1370
#define IDC_IGNORE_REMOVE               1371
#define IDC_AS_ACTION                   1371
#define IDC_IGNORE_CLEAR                1372
#define IDC_AS_RAW_TEXT                 1372
#define IDC_VIEW_BL                     1372
#define IDC_AS_FILETYPE                 1373
#define IDC_PD_LIMITER                  1374
#define IDC_RSX_FAV_GROUPS              1374
#define IDC_RADIO1                      1375
#define IDC_SKIPLIST_DL_GP              1376
#define IDC_SKIPLIST_DOWNLOAD           1377
#define IDC_DIR_EX_NAME                 1378
#define IDC_DIR_EX_PATH                 1379
#define IDC_DIR_EX_EXTENSION            1380
#define IDC_DIR_EX_BROWSE               1381
#define IDC_SDL_SPEED_SPIN              1389
#define IDC_SDL_SPEED                   1390
#define IDC_PROGRESS1                   1391
#define IDC_PM_FLOOD_T                  1392
#define IDC_MYINFO_COUNTER_SPIN         1395
#define IDC_MYINFO_TIME_SPIN            1398
#define IDC_OTHER_QUEUE_OPTIONS         1400
#define IDC_CTE_COUNTER_SPIN            1400
#define IDC_CTE_TIME_SPIN               1402
#define IDC_PM_COUNTER                  1403
#define IDC_PM_COUNTER_SPIN             1404
#define IDC_PM_TIME                     1405
#define IDC_FILELIST_DIFF               1406
#define IDC_SETTINGS_MEBIBYES           1406
#define IDC_PM_TIME_SPIN                1406
#define IDC_SETTINGS_MEBIBITS           1406
#define IDC_RAW_SENDER_SLEEP_TIME       1407
#define IDC_STYLES                      1408
#define IDC_RAW_SENDER_SLEEP_TIME_SPIN  1408
#define IDC_AVAILABLE_STYLES            1409
#define IDC_VAR_NAME                    1409
#define IDC_RAW_VAR_EXAMPLE             1411
#define IDC_RAW_VAR                     1412
#define IDC_AUTOSEARCH_RECHECK_TEXT     1413
#define IDC_TLS_PRIVATE_KEY_FILE        1414
#define IDC_MINIMUM_FILELIST_SIZE_SPIN  1414
#define IDC_TLS_TRUSTED_CERTIFICATES_PATH 1415
#define IDC_MAXIMUM_FILELIST_SIZE_SPIN  1416
#define IDC_SDL_SPEED_BELOW_TEXT        1417
#define IDC_SDL_FOR_MORE_THAN_TEXT      1418
#define IDC_AUTO_REFRESH_TIME           1419
#define IDC_SECONDS                     1419
#define IDC_SETTINGS_AUTO_REFRESH_TIME  1420
#define IDC_BYTE_PER_SEC                1420
#define IDC_AUTO_SEARCH_LIMIT           1421
#define IDC_TLS_OPTIONS                 1421
#define IDC_KICK_DLG_RAW_NAME           1421
#define IDC_KICK_DLG_CMD                1421
#define IDC_SETTINGS_AUTO_SEARCH_LIMIT  1422
#define IDC_GENERATE_CERTS              1422
#define IDC_ACTION_LIST                 1422
#define IDC_CLOSE_ALL_PM                1423
#define IDC_BROWSE_PRIVATE_KEY          1423
#define IDC_SETTINGS_AUTO_SEARCH_LIMIT2 1423
#define IDC_SETTINGS_DOWNCONN           1423
#define IDC_LINE_RAW                    1423
#define IDC_CLOSE_ALL_OFFLINE_PM        1424
#define IDC_BROWSE_CERTIFICATE          1424
#define IDC_DOWNCONN                    1424
#define IDC_CLOSE_ALL_DIR_LIST          1425
#define IDC_BROWSE_TRUSTED_PATH         1425
#define IDC_CLOSE_ALL_SEARCH_FRAME      1426
#define IDC_SOUND_FILE_PATH             1426
#define IDC_SETTINGS_PORT_TLS           1427
#define IDC_MATCH_ALL                   1428
#define IDC_FILTER_HAS_BG_COLOR         1428
#define IDC_CP_ID                       1429
#define IDC_MP_ID                       1430
#define IDC_ADL_POINTS                  1431
#define IDC_FAV_MIN_USERS_LIMIT         1432
#define IDC_FAV_MIN_USERS_LIMIT_SPIN    1433
#define IDC_DIR_EX_NAME_TXT             1434
#define IDC_DIR_EX_EXT_TXT              1435
#define IDC_STARTUP_PRIO_TEXT           1436
#define IDC_STARTUP_PRIO                1437
#define IDC_UPDATE_VERSION              1445
#define IDC_UPDATE_VERSION_CURRENT_LBL  1446
#define IDC_UPDATE_VERSION_LATEST_LBL   1447
#define IDC_UPDATE_VERSION_CURRENT      1448
#define IDC_UPDATE_VERSION_LATEST       1449
#define IDC_UPDATE_HISTORY              1450
#define IDC_HISTORY_STATUS              1451
#define IDC_UPDATE_DOWNLOAD             1452
#define IDC_UPDATE_VERSION2             1454
#define IDC_UPDATE_VERSION_CURRENT_LBL_PROFIL 1455
#define IDC_UPDATE_VERSION_LATEST_LBL_PROFIL 1456
#define IDC_UPDATE_VERSION_LATEST_PROFIL 1457
#define IDC_UPDATE_VERSION_CURRENT_PROFIL 1458
#define IDC_UPDATE_VERSION_CURRENT_PROFIL_MYINFO 1459
#define IDC_UPDATE_VERSION_LATEST_PROFIL_MYINFO 1460
#define IDC_UPDATE                      1462
#define IDC_PROGRESS_MODE               1468
#define IDC_LIST1                       1469
#define IDC_SETTINGS                    1469
#define IDC_FILELISTDP_SELECTOR         1470
#define IDC_COMPILE_TIME                1472
#define IDC_IPW_MODE                    1474
#define IDC_IPW_ISP                     1475
#define IDC_UPDATE_VERSION_CURRENT_IPW  1476
#define IDC_UPDATE_VERSION_LATEST_IPW   1477
#define IDC_FAV_DLG_GROUP               1478
#define IDC_RSX_FAV_EDIT                1483
#define IDC_RSX_FAV_ADD                 1484
#define IDC_RSX_FAV_REMOVE              1485
#define IDC_ABOUT_LINK                  1486
#define IDC_FAV_TABS                    1487
#define IDC_FILELIST_PAGE_LIST_TYPE     1490
#define IDC_LIST2                       1491
#define IDC_PLUGINS_LIST                1491
#define IDC_PARAMS                      1491
#define IDC_DETECT_ID                   1499
#define IDC_PERCENT_FAKE_SHARE_TOLERATED 1504
#define IDC_TIMEOUTS_NO                 1505
#define IDC_DISCONNECTS_NO              1506
#define IDC_DETECTION_ITEM_NAME         1507
#define IDC_ADD_STRING_PAIR_FIRST       1508
#define IDC_MAX_TESTSURS                1509
#define IDC_ADD_STRING_PAIR_FNAME       1509
#define IDC_MAX_FILELISTS               1510
#define IDC_ADD_STRING_PAIR_SNAME       1510
#define IDC_SLEEP_TIME                  1511
#define IDC_BUTTON1                     1511
#define IDC_DETECTION_ITEM_CHANGE       1511
#define IDC_ID_EDIT                     1511
#define IDCOK                           1511
#define IDC_PARENT_ADD                  1511
#define IDC_CHECK_DELAY                 1512
#define IDC_REGEX_TESTER                1513
#define IDC_LEVEL                       1514
#define IDC_INFMAP_TYPE                 1515
#define IDC_SCRIPTS_LIST                1516
#define IDC_USERLIST_COLORS             1517
#define IDC_TABCOLOR_LIST               1522
#define IDC_PROFILE_VERSION_URL         1522
#define IDC_SELECT_TAB_COLOR            1523
#define IDC_PLUGINS_PAGES               1523
#define IDC_SAMPLE_TAB_COLOR            1524
#define IDC_CHAT_BUF_SIZE               1524
#define IDC_RESET_TAB_COLOR             1525
#define IDC_PARENT_REM                  1525
#define IDC_SELECT_STYLES               1526
#define IDC_CHILD_ADD                   1526
#define IDC_CHILD_REM                   1527
#define IDC_CHILD_UP                    1528
#define IDC_CHILD_DOWN                  1529
#define IDC_ACTIONS                     1530
#define IDC_CHILD_EDIT                  1531
#define IDC_PARENT_EDIT                 1532
#define IDC_BUTTON3                     1533
#define IDC_EXPAND                      1533
#define IDC_EXTENSIONS_CFG              1534
#define IDC_TYPE                        1536
#define IDC_TIMEOUT                     1537
#define IDC_TIME_TYPE                   1538
#define IDC_DICTIONARIES                1541
#define IDC_DICTIONARY                  1541
#define IDC_NAT_PMP_GATEWAY             1542
#define WEBSERVER_SOCKET_MESSAGE        1543
#define IDC_SETTINGS_NAT_PMP_GATEWAY    1543
#define IDC_AUTOPRIORITY                1572
#define IDC_SETTINGS_ODC_MENUBAR        1612
#define IDC_SETTINGS_ODC_MENUBAR_USETWO 1613
#define IDC_SETTINGS_ODC_MENUBAR_COLOR  1614
#define IDC_PROGRESS_COLOR_DOWN_SHOW    1616
#define IDC_PROGRESS_COLOR_UP_SHOW      1617
#define IDC_OPEN_DIR                    1618
#define IDC_PREVIEW_APP                 1700
#define IDC_DISCONNECT_RAW              2187
#define IDC_TIMEOUT_RAW                 2188
#define IDC_FAKE_RAW                    2189
#define IDC_RAW_DETECTOR                2189
#define IDC_SHOW_CHEAT                  2190
#define IDC_FILELIST_TOO_SMALL          2191
#define IDC_FILELIST_UNAVAILABLE        2192
#define IDC_TOOLBAR_ADD                 2200
#define IDC_HOTBROWSE                   2201
#define IDC_TOOLBAR_REMOVE              2202
#define IDC_PREVIEW_NAME                2223
#define IDC_PREVIEW_APPLICATION         2224
#define IDC_TOOLBAR_HOT_IMAGE           2224
#define IDC_LIMITER                     2225
#define IDC_STEALTH                     2226
#define IDC_HELP_GEOIPFILE              2227
#define IDC_CHECK_ON_CONNECT            2227
#define IDC_EMOMENU                     2228
#define IDD_FILTER_PAGE                 2275
#define IDD_ADD_FILTER_PAGE             2276
#define IDC_SETTINGS_AUTO_SLOTS         3023
#define IDC_AUTO_SLOTS                  3024
#define IDC_AUTO_SLOTS_SPIN             3025
#define IDC_SETTINGS_PARTIAL_SLOTS      3026
#define IDC_PARTIAL_SLOTS               3027
#define IDC_PARTIAL_SLOTS_SPIN          3028
#define IDC_PAUSE                       3140
#define IDC_DOWNLOAD_TARGET             5000
#define IDC_DOWNLOAD_TARGET_DIR         5500
#define IDC_SELECT_WINDOW               6000
#define IDC_USER_COMMAND                6500
#define IDC_PRIORITY_PAUSED             7000
#define IDC_PRIORITY_LOWEST             7001
#define IDC_PRIORITY_LOW                7002
#define IDC_PRIORITY_NORMAL             7003
#define IDC_PRIORITY_HIGH               7004
#define IDC_PRIORITY_HIGHEST            7005
#define IDC_DOWNLOAD_WHOLE_TARGET       7500
#define IDC_DOWNLOAD_FAVORITE_DIRS      8500
#define IDC_DOWNLOAD_WHOLE_FAVORITE_DIRS 9000
#define IDR_TRAY_PM                     10000
#define IDC_EXTRASLOTSSPIN              10002
#define IDC_EXTRA_DOWN_SLOT             10003
#define IDC_EXTRA_DOWNLOADS_MAX         10004
#define IDC_ERROR_COLOR                 10005
#define IDC_UPTIME                      10007
#define IDD_LIMITPAGE                   10008
#define IDC_CZDC_SLOW_DISCONNECT        10009
#define IDC_STRONGDC_SLOW_DISCONNECT    10009
#define IDC_CZDC_I_DOWN_SPEED           10010
#define IDC_STRONGDC_I_DOWN_SPEED       10010
#define IDC_BACK_COLOR                  10011
#define IDC_REMOVE_IF                   10011
#define IDC_CZDC_TIME_DOWN              10013
#define IDC_STRONGDC_TIME_DOWN          10013
#define IDC_TEXT_STYLE                  10014
#define IDC_TEXT_COLOR                  10015
#define IDC_CZDC_H_DOWN_SPEED           10016
#define IDC_STRONGDC_H_DOWN_SPEED       10016
#define IDC_PREVIEW                     10017
#define IDC_CZDC_MIN_FILE_SIZE          10017
#define IDC_STRONGDC_MIN_FILE_SIZE      10017
#define IDC_I_DOWN_SPEED                10018
#define IDC_TEXT_STYLES                 10019
#define IDC_REMOVE_IF_BELOW             10019
#define IDC_EXTRA_SLOTS                 10020
#define IDC_SDL_TIME                    10020
#define IDC_EXTRA_SLOTS_SPIN            10021
#define IDC_SMALL_FILE_SIZE             10022
#define IDC_SMALL_FILE_SIZE_SPIN        10023
#define IDC_BLACK_AND_WHITE             10024
#define IDC_DEFAULT_STYLES              10025
#define IDC_COPY_TAG                    10026
#define IDC_COPY_FILENAME               10027
#define IDC_COPY_PATH                   10028
#define IDC_TIME_DOWN                   10029
#define IDC_COPY_SIZE                   10030
#define ID_VIEW_TRANSFER_VIEW           10031
#define IDC_OPEN_HUB_LOG                10032
#define IDC_OPEN_USER_LOG               10033
#define IDC_H_DOWN_SPEED                10034
#define IDC_SETTINGS_KBPS5              10035
#define IDC_SETTINGS_KBPS7              10036
#define IDC_UPLOADSPEEDSPIN             10038
#define IDC_DOWNLOADSPEEDSPIN           10039
#define IDC_NONE                        10041
#define IDD_TEXT_STYLES                 10042
#define IDC_SETTINGS_KBPS6              10043
#define IDD_KICK                        10044
#define IDC_SETTINGS_MB                 10044
#define IDD_RSX                         10045
#define IDC_SETTINGS_MINUTES            10046
#define IDD_RSXADVANCED                 10046
#define IDC_I_DOWN_SPEED_SPIN           10047
#define IDD_DIR_EX_DLG                  10047
#define IDC_TIME_DOWN_SPIN              10048
#define IDD_ADD_HL                      10048
#define IDC_H_DOWN_SPEED_SPIN           10049
#define IDC_PUBLIC_MESSAGE              10050
#define IDC_MIN_FILE_SIZE_SPIN          10050
#define IDD_KICK_DLG                    10050
#define IDC_SELECT_USER                 10051
#define IDC_REMOVE_SPIN                 10051
#define IDD_ADD_ADLSP_RANGE             10051
#define IDC_COPY_ACTUAL_LINE            10052
#define IDC_SDL_TIME_SPIN               10052
#define IDD_FAV_TAB_OP                  10052
#define IDC_COPY_DESCRIPTION            10053
#define IDD_FAV_TAB_CUSTOM              10053
#define IDC_COPY_EMAIL_ADDRESS          10054
#define IDD_SCRIPTS_LIST                10054
#define IDC_AUTOSCROLL_CHAT             10055
#define IDD_FAV_TAB_PLUGINS             10055
#define IDD_FAV_TAB_RAWSETTINGS         10055
#define IDC_WHOIS_IP                    10056
#define IDC_BAN_IP                      10057
#define IDD_EXTENSIONS_CFG              10057
#define IDC_UNBAN_IP                    10058
#define IDC_CLIENT                      10059
#define IDC_COPY_URL                    10060
#define IDC_BOLD_AUTHOR_MESS            10061
#define IDC_IGNORE                      10063
#define IDC_UNIGNORE                    10064
#define IDC_WINAMP_HELP                 10065
#define IDC_MX_UP_SP_LMT_NORMAL         10069
#define IDC_MX_DW_SP_LMT_NORMAL         10070
#define IDC_MX_UP_SP_LMT_TIME           10071
#define IDC_MX_DW_SP_LMT_TIME           10072
#define IDC_TIME_LIMITING               10073
#define IDC_BW_START_TIME               10074
#define IDC_BW_END_TIME                 10075
#define IDC_UPLOADSPEEDSPIN_TIME        10077
#define IDC_DOWNLOADSPEEDSPIN_TIME      10078
#define IDC_GRANTSLOT                   10080
#define IDC_GRANTSLOT_HOUR              10081
#define IDC_GRANTSLOT_DAY               10082
#define IDC_GRANTSLOT_WEEK              10083
#define IDC_UNGRANTSLOT                 10084
#define IDC_UPLOAD_QUEUE                10085
#define IDC_THROTTLE_ENABLE             10093
#define IDC_DISCONNECTING_ENABLE        10094
#define IDC_WINAMP                      10095
#define IDC_SEGMENTED_ONLY              10095
#define ID_VIEW_PLUGIN_TOOLBAR          10096
#define IDC_VIEW_PLUGINS_LIST           10097
#define IDC_VIEW_SCRIPTS_LIST           10098
#define IDC_PROGRESS_TEXT_COLOR_DOWN    10102
#define IDC_PROGRESS_TEXT_COLOR_UP      10103
#define IDC_CZDC_PM_SOUND               10107
#define IDC_STRONGDC_PM_SOUND           10107
#define IDC_CZDC_TRANSFER_LIMITING      10108
#define IDC_STRONGDC_TRANSFER_LIMITING  10108
#define IDC_CZDC_UP_SPEEED              10109
#define IDC_CZDC_UP_SPEED               10109
#define IDC_STRONGDC_UP_SPEED           10109
#define IDC_CZDC_DW_SPEEED              10110
#define IDC_CZDC_DW_SPEED               10110
#define IDC_STRONGDC_DW_SPEED           10110
#define IDC_CZDC_TO                     10111
#define IDC_STRONGDC_TO                 10111
#define IDC_CZDC_SECONDARY_TRANSFER     10112
#define IDC_CZDC_UP_NOTE                10113
#define IDC_STRONGDC_UP_NOTE            10113
#define IDC_CZDC_DW_NOTE                10114
#define IDC_STRONGDC_DW_NOTE            10114
#define IDC_CZDC_PROGRESS_COLOR         10115
#define IDC_STRONGDC_PROGRESS_COLOR     10115
#define IDC_CZDC_PROGRESS_TEXT          10117
#define IDC_INTERVAL_TEXT               10118
#define IDC_MATCH_QUEUE_TEXT            10119
#define IDC_CZDC_WINAMP                 10120
#define IDC_SETCZDC_PM_LINES            10121
#define IDC_STRONGDC_PM_LINES           10121
#define IDC_SETSTRONGDC_PM_LINES        10121
#define IDC_CZDC_PREVIEW                10123
#define IDC_STRONGDC_PREVIEW            10123
#define IDC_CZDC_DW_SPEEED1             10124
#define IDC_CZDC_DW_SPEED1              10124
#define IDC_STRONGDC_DW_SPEED1          10124
#define IDC_CZDC_UP_SPEEED1             10125
#define IDC_CZDC_UP_SPEED1              10125
#define IDC_STRONGDC_UP_SPEED1          10125
#define IDC_SETTINGS_KBPS1              10126
#define IDC_SETTINGS_KBPS2              10127
#define IDC_SETTINGS_KBPS3              10128
#define IDC_SETTINGS_KBPS4              10129
#define IDC_CZDC_SMALL_SLOTS            10130
#define IDC_STRONGDC_SMALL_SLOTS        10130
#define IDC_CZDC_SMALL_SIZE             10131
#define IDC_STRONGDC_SMALL_SIZE         10131
#define IDC_CZDC_NOTE_SMALL             10132
#define IDC_STRONGDC_NOTE_SMALL         10132
#define IDC_USER_CMD_DESCRIPTION        10140
#define IDC_USER_CMD_EXAMPLE            10141
#define IDC_COPY_EXACT_SHARE            10145
#define IDC_COPY_IP                     10146
#define IDC_COPY_NICK_IP                10147
#define IDC_PM_LINES                    10147
#define IDC_COPY_ALL                    10148
#define IDC_PM_LINESSPIN                10148
#define IDC_CHECKLIST                   10150
#define ID_GET_TTH                      10151
#define IDC_COPY_LINK                   10152
#define IDC_REBUILD_TOOLBAR             10162
#define IDC_REBUILD_PLUGIN_TOOLBAR      10163
#define IDC_MAGNET_SIZE                 10164
#define IDC_MAGNET_DISP_SIZE            10165
#define IDC_TIMESTAMP_HELP              10167
#define IDC_USERLIST_DBLCLICK           10190
#define IDC_TRANSFERLIST_DBLCLICK       10191
#define IDC_USERLISTDBLCLICKACTION      10192
#define IDC_TRANSFERLISTDBLCLICKACTION  10193
#define IDC_CHATDBLCLICKACTION          10194
#define IDC_CHAT_DBLCLICK               10195
#define IDC_HEADER_MENU                 10196
#define IDC_COPY_SUB_EXACT_SHARE        11001
#define IDC_COPY_SUB_DESCRIPTION        11002
#define IDC_COPY_SUB_TAG                11003
#define IDC_COPY_SUB_EMAIL_ADDRESS      11004
#define IDC_COPY_SUB_IP                 11005
#define IDC_COPY_SUB_CONNECTION         11006
#define IDC_COPY_SUB_MYINFO             11007
#define IDC_COPY_SUB_CLIENT             11008
#define IDC_COPY_SUB_CHEAT              11009
#define IDC_COPY_SUB_HOST               11010
#define IDC_COPY_SUB_CID                11011
#define IDC_COPY_CONNECTION             11012
#define IDC_COPY_MYINFO                 11013
#define IDC_COPY_CLIENT                 11014
#define IDC_COPY_CHEAT                  11015
#define IDC_COPY_HOST                   11016
#define IDC_COPY_CID                    11017
#define ID_SHELLCONTEXTMENU_MIN         12000
#define ID_SHELLCONTEXTMENU_MAX         14000
#define IDC_BITZI_LOOKUP                20000
#define IDC_BROWSELIST                  21000
#define IDC_REMOVE_SOURCE               23000
#define IDC_PM                          25000
#define IDC_READD                       27000
#define IDC_REMOVE_SOURCES              29000
#define ID_FILE_CONNECT                 32772
#define ID_FILE_SETTINGS                32774
#define ID_FILE_RECONNECT               32775
#define ID_FILE_SEARCH                  32776
#define ID_FILE_QUICK_CONNECT           32777
#define IDC_DOWNLOAD                    32780
#define IDC_DOWNLOADTO                  32781
#define IDC_RECENTS                     32782
#define IDC_FAVORITES                   32783
#define IDC_FOLLOW                      32784
#define IDC_SEND_MESSAGE                32786
#define IDC_FILTER_FOCUS                32788
#define IDC_GET_USER_RESPONSES          32789
#define IDC_REPORT                      32790
#define IDC_CLEAN_USER_D                32791
#define IDC_SET_PROTECTED_USER          32792
#define IDC_UNSET_PROTECTED_USER        32793
#define IDC_CUSTOM_KICK                 32794
#define IDC_MULTIHUB_KICK               32795
#define ID_SWINDOW_1                    32796
#define ID_SWINDOW_2                    32797
#define ID_SWINDOW_3                    32798
#define ID_SWINDOW_4                    32799
#define ID_SWINDOW_5                    32800
#define ID_SWINDOW_6                    32801
#define ID_SWINDOW_7                    32802
#define ID_SWINDOW_8                    32803
#define ID_SWINDOW_9                    32804
#define ID_SWINDOW_0                    32805
#define IDC_DIR_EX_NAME_TEXT            32816
#define IDC_DIR_EX_PATH_TEXT            32817
#define IDC_DIR_EX_EXT_TEXT             32818
#define ID_WINDOW_MINIMIZE_ALL          57654
#define ID_WINDOW_RESTORE_ALL           57655
#define IDC_CHATCOLORS                  65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        355
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1544
#define _APS_NEXT_SYMED_VALUE           134
#endif
#endif
